import {decimal,displayName} from '../utils/format'
import {NavLink,Outlet,Navigate} from 'react-router-dom'
import {LayoutDashboard,Layers3,Vote,Network,ShieldCheck,BookOpen,UserRound,Settings,LogOut,PanelLeftClose,PanelLeftOpen,GraduationCap,Plus} from 'lucide-react'
import {useState} from 'react'
import {useAuth} from '../auth/AuthContext'
import {Loading} from './UI'
const nav=[['/','Genel bakış',LayoutDashboard],['/topics','Konular',Layers3],['/votes','Oylamalar',Vote],['/engineering','Analiz ve tasarım',BookOpen],['/graph','İlişki haritası',Network],['/ledger','Kayıt defteri',ShieldCheck],['/rules','Yönetmelikler',BookOpen],['/profile','Profilim',UserRound]] as const
export function Layout(){const {user,loading,logout}=useAuth();const [open,setOpen]=useState(false);if(loading)return <Loading/>;if(!user)return <Navigate to="/login" replace/>
return <div className="app-shell"><aside className={`sidebar ${open?'open':''}`}><NavLink className="brand" to="/"><span className="brand-icon"><GraduationCap/></span><span>Müşterek<small>Öğrenme ve karar platformu</small></span></NavLink><div className="workspace-label">ÇALIŞMA ALANI</div><nav>{nav.map(([to,label,Icon])=><NavLink end={to==='/'} key={to} to={to} onClick={()=>setOpen(false)}><Icon size={19}/>{label}</NavLink>)}</nav>{user.role==='ADMIN'&&<><div className="workspace-label">YÖNETİM</div><nav><NavLink to="/admin" onClick={()=>setOpen(false)}><Settings size={19}/>Yönetim paneli</NavLink></nav></>}<div className="sidebar-bottom"><div className="semester"><span className="live-dot"/>2026 / Güz dönemi<small>Üniversite çalışma alanı</small></div><button className="logout" onClick={logout}><LogOut size={17}/>Çıkış yap</button></div></aside>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}<div className="main-shell"><header className="topbar"><button className="icon-button menu-toggle" aria-label="Menüyü aç veya kapat" onClick={()=>setOpen(!open)}>{open?<PanelLeftClose/>:<PanelLeftOpen/>}</button><span className="topbar-context">Müşterek <span>/</span> Katılımcı Karar Sistemi</span><div className="topbar-user"><span className="score">{user.points} <small>puan</small></span><span className="coefficient">r {decimal(user.reputation_coefficient)}</span><span className="avatar">{user.first_name[0]}{user.last_name[0]}</span><div><strong>{user.first_name} {user.last_name}</strong><small>{user.team||'Takım seçilmedi'} · {displayName(user.role)}</small></div></div></header><main><Outlet/></main><footer className="app-footer"><span>Müşterek · Üniversite Prototipi</span><span>Akran öğrenme ve katılımcı karar alma</span></footer></div></div>}
export function AdminGuard(){const {user}=useAuth();return user?.role==='ADMIN'?<Outlet/>:<Navigate to="/" replace/>}
export const NewTopicLink=()=> <NavLink className="button primary" to="/topics/new"><Plus size={18}/>Konu öner</NavLink>
