import {displayName} from '../utils/format'
import {useState,type FormEvent} from 'react'
import {Link,Navigate,useNavigate} from 'react-router-dom'
import {GraduationCap,Users,ShieldCheck,Network} from 'lucide-react'
import {api,errorText} from '../api/client'
import {useAuth} from '../auth/AuthContext'
import {useApi} from '../hooks/useApi'
import type {Tag} from '../types'
import {Notice} from '../components/UI'
export function AuthPage({register=false}:{register?:boolean}){const {user,setUser}=useAuth();const navigate=useNavigate();const {data:meta}=useApi<{teams:Tag[];tags:Tag[]}>('/metadata');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [tags,setTags]=useState<number[]>([])
 if(user)return <Navigate to="/" replace/>
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const body:Record<string,unknown>={email:f.get('email'),password:f.get('password')};if(register)Object.assign(body,{first_name:f.get('first_name'),last_name:f.get('last_name'),username:f.get('username'),birth_date:f.get('birth_date')||null,address:f.get('address'),team_id:f.get('team_id')?Number(f.get('team_id')):null,tag_ids:tags});try{const {data}=await api.post(`/auth/${register?'register':'login'}`,body);sessionStorage.setItem('token',data.access_token);setUser(data.user);navigate('/')}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <div className="auth-shell"><section className="auth-story"><div className="brand"><GraduationCap size={34}/><span>Müşterek</span></div><div><div className="eyebrow">KATILIMCI KAMPÜS</div><h1>Akran öğrenme{' '}<br/>ve katılımcı{' '}<br/><em>karar alma.</em></h1><p>Konu önerileri, tartışmalar ve kurul değerlendirmeleri için ortak çalışma alanı.</p><div className="auth-values"><span><Users/>Eşit katılım</span><span><ShieldCheck/>Şeffaf kararlar</span><span><Network/>Birlikte öğrenme</span></div></div><small>Akran Öğrenme ve Katılımcı Karar Alma Sistemi</small></section><section className="auth-form"><div><span className="eyebrow">KULLANICI HESABI</span><h2>{register?'Topluluğa katıl':'Giriş yap'}</h2><p>{register?'Profilini oluştur ve ortak kararlara katıl.':'Hesabına giriş yap, ortak çalışmalara katıl.'}</p>{error&&<Notice>{error}</Notice>}<form onSubmit={submit}>{register&&<><div className="form-grid"><label>Ad<input name="first_name" required maxLength={80}/></label><label>Soyad<input name="last_name" required maxLength={80}/></label></div><label>Kullanıcı adı<input name="username" required minLength={3} maxLength={80}/></label></>}<label>E-posta<input name="email" type="email" autoComplete="email" required defaultValue={!register?'user@example.com':''}/></label><label>Şifre<input name="password" type="password" autoComplete={register?'new-password':'current-password'} required minLength={register?8:1} maxLength={128} defaultValue={!register?'Demo12345!':''}/></label>{register&&<><div className="form-grid"><label>Doğum tarihi<input name="birth_date" type="date"/></label><label>Takım<select name="team_id"><option value="">Takımsız</option>{meta?.teams.map(t=><option key={t.id} value={t.id}>{displayName(t.name)}</option>)}</select></label></div><label>Adres<input name="address" maxLength={500} placeholder="Demo adres kullanabilirsin"/></label><label>İlgi ve uzmanlık alanları</label><div className="tag-options">{meta?.tags.map(t=><label key={t.id}><input type="checkbox" checked={tags.includes(t.id)} onChange={e=>setTags(e.target.checked?[...tags,t.id]:tags.filter(i=>i!==t.id))}/>{displayName(t.name)}</label>)}</div></>}<button className="button primary full" disabled={busy}>{busy?'İşleniyor…':register?'Hesap oluştur':'Giriş yap'}</button></form><p className="auth-switch">{register?'Zaten hesabın var mı?':'Henüz hesabın yok mu?'} <Link to={register?'/login':'/register'}>{register?'Giriş yap':'Hesap oluştur'}</Link></p>{!register&&<div className="demo-box"><strong>Demo hesapları</strong><span>user@example.com · Katılımcı</span><span>expert@example.com · Bilirkişi</span><span>admin@example.com · Yönetici</span><small>Ortak şifre: Demo12345!</small></div>}</div></section></div>}
