import {useEffect, useState} from 'react'
import {useSearchParams, Link} from 'react-router-dom'
import {SequenceDiagram} from '../components/SequenceDiagram'
import {ReactFlow, Background, Controls, MarkerType, type Node, type Edge} from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import {useAuth} from '../auth/AuthContext'
import {api, errorText} from '../api/client'
import {Heading, Loading, Notice} from '../components/UI'
import '../engineering.css'

const fields = [
  ['business_goal','İş hedefi ve değer','Kimin hangi sorunu çözülüyor? İş metriği ne?'],
  ['decision','Karar ve eylem','Öneriyi kim, hangi kararda kullanacak?'],
  ['task','ML görevi','Girdi → çıktı, görev türü ve etiket tanımı.'],
  ['data','Veri','Kaynak, miktar, etiketleme, erişim izni ve KVKK.'],
  ['metrics','Metrikler','Model, ürün ve koruyucu metrikler; hata maliyeti.'],
  ['baseline','Baseline','Mevcut çözüm, basit kural ve ölçülen değerler.'],
  ['constraints','Kısıtlar','Zaman, bütçe, gecikme, donanım ve yasal sınırlar.'],
  ['risks','Riskler ve başarı tanımı','Ön-otopsi ve yayına alma koşulları.'],
] as const
type Canvas = {id:number; fields:Record<string,string>; updated_at:string|null; updated_by:number|null}
type Method = {id:string; name:string; accuracy:number; macro_f1:number; coverage:number; latency_p95_ms:number; per_class:{label:string;precision:number;recall:number;f1:number;support:number}[]; confusion_matrix:number[][]; errors:{id:string;text:string;expected:string;predicted:string}[]}
type Evaluation = {dataset:{version:string;source:string;sha256:string;size:number;limitations:string|string[]};labels:string[];distribution:{label:string;count:number}[];methods:Method[]}
const labels:Record<string,string> = {COMMUNITY:'Topluluk',DEPARTMENT:'Bölüm',FACULTY:'Fakülte',UNIVERSITY:'Üniversite',REVIEW:'İnsan incelemesi'}
const label = (value:string) => labels[value] || value
const percent = (value:number) => new Intl.NumberFormat('tr-TR',{style:'percent',maximumFractionDigits:1}).format(value)

export function Engineering(){
  const [params,setParams]=useSearchParams()
  const requested=params.get('tab')||'canvas'
  const tab=['canvas','evaluation','design'].includes(requested)?requested:'canvas'
  const setTab=(value:string)=>setParams(previous=>{previous.set('tab',value);return previous})
  return <div className="engineering"><Heading eyebrow="PROBLEM · ÖLÇÜM · TASARIM" title="Mühendislik çalışma alanı" description="Karar desteğinin sınırlarını tanımla, basit çözümlerle karşılaştır ve sistemin tasarımını incele."/>
    <div className="eng-tabs" role="tablist" aria-label="Mühendislik bölümleri">{[['canvas','Problem kanvası'],['evaluation','Ölçüm ve hata analizi'],['design','Tasarım diyagramları']].map(([id,text])=><button key={id} id={`tab-${id}`} role="tab" aria-selected={tab===id} aria-controls={`panel-${id}`} onClick={()=>setTab(id)}>{text}</button>)}</div>
    <section id="panel-canvas" role="tabpanel" aria-labelledby="tab-canvas" hidden={tab!=='canvas'}><ProblemCanvas/></section>
    <section id="panel-evaluation" role="tabpanel" aria-labelledby="tab-evaluation" hidden={tab!=='evaluation'}><EvaluationPanel/></section>
    {tab==='design'&&<section id="panel-design" role="tabpanel" aria-labelledby="tab-design"><DesignPanel/></section>}
  </div>
}

function ProblemCanvas(){
  const {user}=useAuth(); const admin=user?.role==='ADMIN'
  const [canvas,setCanvas]=useState<Canvas|null>(null),[draft,setDraft]=useState<Record<string,string>>({})
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
  useEffect(()=>{let active=true;api.get<Canvas>('/engineering/canvas').then(({data})=>{if(active){setCanvas(data);setDraft(data.fields)}}).catch(e=>{if(active)setError(errorText(e))});return()=>{active=false}},[])
  async function save(){setBusy(true);setError('');setMessage('');try{const {data}=await api.put<Canvas>('/engineering/canvas',{fields:draft});setCanvas(data);setDraft(data.fields);setMessage('Problem kanvası kaydedildi.')}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  return <>{error&&<Notice>{error}</Notice>}{message&&<Notice kind="info">{message}</Notice>}
    <div className="eng-intro"><div><h2>Önce problem, sonra çözüm</h2><p>Bu kanvas proje varsayımlarını ve kabul koşullarını tutar. Hedefler birer öneridir; ölçülmüş sonuçlar ayrı sekmede hesaplanır.</p></div><span className="eng-chip">8 alan · tek problem</span></div>
    {!canvas&&!error?<Loading/>:canvas&&<><div className="eng-canvas-grid">{fields.map(([key,title,hint],index)=><article className="panel eng-canvas-card" key={key}><div className="eng-card-heading"><span>{String(index+1).padStart(2,'0')}</span><label htmlFor={`canvas-${key}`}>{title}</label></div><p>{hint}</p><textarea id={`canvas-${key}`} value={draft[key]||''} readOnly={!admin} minLength={10} maxLength={3000} rows={5} onChange={e=>{setDraft({...draft,[key]:e.target.value});setMessage('')}}/></article>)}</div>
      <div className="eng-save"><p>{admin?'Yönetici olarak bu ortak kanvası düzenleyebilirsin.':'Kanvas tüm üyelere açıktır; düzenleme yetkisi yöneticidedir.'}{canvas.updated_at&&<small>Son kayıt: {new Date(canvas.updated_at).toLocaleString('tr-TR')}</small>}</p>{admin&&<button className="button primary" disabled={busy||fields.some(([key])=>(draft[key]||'').trim().length<10)||(!!canvas.updated_at&&JSON.stringify(canvas.fields)===JSON.stringify(draft))} onClick={save}>{busy?'Kaydediliyor…':'Kanvası kaydet'}</button>}</div></>}
    <p className="eng-source">Ders kaynağı: YZM_Hafta02_Problem_Cerceveleme.pdf · fiziksel sayfa 48, “Tek sayfalık problem tanım kanvası”.</p>
  </>
}

function EvaluationPanel(){
  const [data,setData]=useState<Evaluation|null>(null),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
  async function run(){setBusy(true);setError('');try{const result=await api.get<Evaluation>('/engineering/evaluation');setData(result.data);setSelected(result.data.methods[result.data.methods.length-1]?.id||'')}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  const method=data?.methods.find(m=>m.id===selected)
  return <><div className="eng-intro"><div><h2>Öneri kalitesini ölç</h2><p>Aynı etiketli örneklerde baseline ve kapsam önericisini karşılaştır. Bu deney, karar yetkisini veya oylama sonucunu değiştirmez.</p></div><button className="button primary" disabled={busy} onClick={run}>{busy?'Ölçülüyor…':data?'Deneyi yeniden çalıştır':'Değerlendirmeyi çalıştır'}</button></div>
    <Notice kind="info">Bu prototipin önericisi deterministik kurallarla çalışır; eğitilmiş bir temel model değildir. Sentetik test başarısı gerçek kullanıcı verisindeki başarıyı kanıtlamaz.</Notice>
    {error&&<Notice>{error}</Notice>}{busy&&<Loading/>}
    {!data&&!busy&&<div className="panel eng-empty"><h3>Henüz bu oturumda ölçüm yapılmadı</h3><p>Deneyi çalıştırdığında doğruluk, macro-F1, kapsama, gecikme ve örnek bazında hatalar burada görünecek.</p><span className="eng-chip">Hedef ≠ ölçülen sonuç</span></div>}
    {data&&<><div className="panel eng-dataset"><div><span className="eyebrow">DENEY VERİSİ</span><h3>{data.dataset.version} · {data.dataset.size} örnek</h3><p>{data.dataset.source}</p></div><div className="eng-distribution">{data.distribution.map(d=><span key={d.label}>{label(d.label)} <strong>{d.count}</strong></span>)}</div><details><summary>Veri sınırları ve yeniden üretilebilirlik</summary><p>{Array.isArray(data.dataset.limitations)?data.dataset.limitations.join(' '):data.dataset.limitations}</p><p>SHA-256: <code>{data.dataset.sha256}</code></p></details></div>
      <div className="panel"><h3>Aynı veri, farklı yöntemler</h3><div className="eng-table-scroll"><table className="eng-table"><thead><tr><th>Yöntem</th><th>Doğruluk</th><th>Macro-F1</th><th>Kapsama</th><th>P95 gecikme</th></tr></thead><tbody>{data.methods.map(m=><tr key={m.id}><th>{m.name}</th><td>{percent(m.accuracy)}</td><td>{m.macro_f1.toFixed(3)}</td><td>{percent(m.coverage)}</td><td>{m.latency_p95_ms.toLocaleString('tr-TR',{maximumFractionDigits:3})} ms</td></tr>)}</tbody></table></div><p className="eng-caption">Kapsama: REVIEW yerine dört kapsamdan biri önerilen örnek oranı. Tüm öneriler insan onayı gerektirir. Macro-F1 dört kapsam sınıfının ortalamasıdır; REVIEW bir çekimserlik çıktısıdır. Gecikme bu sunucudaki yerel çalıştırmaya aittir; uçtan uca kullanıcı gecikmesi değildir.</p></div>
      <div className="eng-method"><label htmlFor="evaluation-method">Ayrıntıları gösterilecek yöntem</label><select id="evaluation-method" value={selected} onChange={e=>setSelected(e.target.value)}>{data.methods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></div>
      {method&&<><div className="panel"><h3>Karışıklık matrisi</h3><p className="eng-caption">Satırlar beklenen etiket, sütunlar tahmin. Köşegen üzerindeki değerler doğru tahminlerdir.</p><div className="eng-table-scroll"><table className="eng-table eng-matrix"><thead><tr><th>Beklenen ↓ / Tahmin →</th>{data.labels.map(l=><th key={l}>{label(l)}</th>)}</tr></thead><tbody>{data.labels.map((l,i)=><tr key={l}><th>{label(l)}</th>{data.labels.map((other,j)=><td className={i===j?'correct':''} key={other}>{method.confusion_matrix[i]?.[j]??0}</td>)}</tr>)}</tbody></table></div></div>
        <div className="panel"><h3>Sınıf bazında sonuçlar</h3><div className="eng-table-scroll"><table className="eng-table"><thead><tr><th>Sınıf</th><th>Kesinlik</th><th>Duyarlılık</th><th>F1</th><th>Örnek</th></tr></thead><tbody>{method.per_class.map(c=><tr key={c.label}><th>{label(c.label)}</th><td>{percent(c.precision)}</td><td>{percent(c.recall)}</td><td>{c.f1.toFixed(3)}</td><td>{c.support}</td></tr>)}</tbody></table></div></div>
        <div className="panel"><h3>Hata analizi · {method.errors.length} yanlış tahmin / incelemeye bırakma</h3><p className="eng-caption">Bu örnekler hata incelemesi içindir. Kuralları bu sete göre değiştirmek bağımsız test güvencesini azaltır; sonraki doğrulama için ayrı gerçek veri gerekir.</p>{!method.errors.length?<p>Bu sette yanlış tahmin yok. Bu sonuç, tüm girdilerde hatasızlık anlamına gelmez.</p>:<div className="eng-errors">{method.errors.map(e=><article key={e.id}><small>Örnek {e.id}</small><p>{e.text}</p><div><span>Beklenen: <strong>{label(e.expected)}</strong></span><span>Tahmin: <strong>{label(e.predicted)}</strong></span></div></article>)}</div>}</div></>}
    </>}
  </>
}

function graphNode(id:string,x:number,y:number,title:string,body:string,actor=false):Node{return {id,position:{x,y},data:{label:<div><strong>{title}</strong><span>{body}</span></div>},style:{width:220,borderRadius:actor?80:10,border:'1px solid #8aab9b',background:actor?'#e9f1ec':'#fff',fontSize:13,color:'#173b2b'}}}
function edge(source:string,target:string,label:string,dashed=false):Edge{return {id:`${source}-${target}-${label}`,source,target,label,type:'smoothstep',markerEnd:{type:MarkerType.ArrowClosed},style:{stroke:'#587869',strokeDasharray:dashed?'5 4':undefined},labelStyle:{fontSize:11,fill:'#204332'},labelBgPadding:[6,4]}}
const diagrams:Record<string,{title:string;description:string;nodes:Node[];edges:Edge[];notes:string[]}>= {
  state:{title:'Durum diyagramı · konu yaşam döngüsü',description:'Konunun kalıcı durum geçişleri. Yönetmelik durumu, kabul durumundan ayrı tutulur.',nodes:[graphNode('proposed',0,100,'PROPOSED','Öneri oluşturuldu'),graphNode('voting',310,100,'VOTING','Eşit oylar toplanır'),graphNode('accepted',670,0,'ACCEPTED','Kabul edildi; politika ayrıca kontrol edilir'),graphNode('rejected',670,220,'REJECTED','Yeterli çoğunluk yok')],edges:[edge('proposed','voting','Yetkili yönetici başlatır'),edge('voting','accepted','Katılım + çoğunluk + grup desteği'),edge('voting','rejected','Katılım yeterli, çoğunluk yok')],notes:['Katılım üçten azsa sonuçlandırma 409 döner ve VOTING korunur.','Çoğunluk var ama etkilenen takım desteği yetersizse VOTING kalır ve MINORITY_CONFLICT kaydedilir.','ACCEPTED tek başına uygulanabilir demek değildir: engelleyici politika veya bekleyen uzman talebi bulunmamalıdır.','Kod: services/decisions.py — close_vote; routers/api.py — start_voting ve topic_json.']},
  classes:{title:'Sınıf diyagramı · alan modeli',description:'Kalıcı modelin temel ilişkileri. Oklar ilişki yönünü gösterir; çokluklar bağlantı etiketlerindedir.',nodes:[graphNode('user',0,0,'User','id · role · team_id · authorities'),graphNode('topic',360,0,'Topic','id · status · decision_scope'),graphNode('vote',0,200,'Vote','user_id · topic_id · choice'),graphNode('review',360,200,'ExpertReview','expert_id · topic_id · recommendation'),graphNode('rule',720,0,'Rule','condition · severity'),graphNode('check',720,200,'RuleCheck','topic_id · rule_id · status')],edges:[edge('user','topic','1 oluşturur 0..*'),edge('user','vote','1 kullanır 0..*'),edge('topic','vote','1 alır 0..*'),edge('topic','review','1 alır 0..*'),edge('user','review','1 yazar 0..*'),edge('rule','check','1 için 0..*'),edge('topic','check','1 için 0..*')],notes:['Vote ayrıca alt konu veya silme önerisini hedefleyebilir; bu görünüm ana konu akışını sadeleştirir.','Yetki yalnızca role bağlı değildir: kurul kapsamı, ilgi alanı ve takım ilişkisi servislerde denetlenir.']},
  usecases:{title:'Kullanım durumu diyagramı',description:'Aktörler ve sistemde başlattıkları işlemler. Kurul üyeliği ayrı bir rol değil, kullanıcıya verilen kapsam yetkisidir.',nodes:[graphNode('member',0,0,'Üye','Sisteme giriş yapan kullanıcı',true),graphNode('expert',0,190,'Bilirkişi','EXPERT + ilgili uzmanlık alanı',true),graphNode('admin',0,380,'Yönetici','ADMIN',true),graphNode('propose',370,0,'Konu öner','Gerekçe ve karar kapsamı'),graphNode('vote',370,140,'Oy kullan','Yetki + uygunluk kontrolü'),graphNode('review',370,280,'Uzman görüşü ver','Uzmanlık ve kapsam kontrolü'),graphNode('manage',370,420,'Yönetimi yapılandır','Kural, yetki, problem kanvası'),graphNode('board',720,0,'Yetkili kurul üyesi','Kapsama atanmış kullanıcı',true),graphNode('decision',720,240,'Oylamayı sonuçlandır','Yetki ve karar koşulları')],edges:[edge('member','propose','başlatır'),edge('member','vote','uygunsa'),edge('expert','review','başlatır'),edge('admin','manage','başlatır'),edge('board','vote','kendi kapsamında'),edge('board','decision','yetkisi varsa')],notes:['Tüm kullanıcılar mühendislik alanını okuyabilir; problem kanvasını yalnızca yönetici düzenler.','Kullanım durumları yetki kontrollerinin yerine geçmez; sunucu her istekte denetim yapar.']},
  strategy:{title:'Bağımlılık grafı · GoF Strategy',description:'PolicyEngine somut algoritmalar yerine RuleStrategy sözleşmesine bağlıdır. Yeni koşul algoritması kayıt tablosuna eklenebilir.',nodes:[graphNode('api',0,0,'API router','HTTP · kimlik · girdi doğrulama'),graphNode('decisions',310,0,'decisions servisi','Karar akışını koordine eder'),graphNode('engine',620,0,'PolicyEngine','evaluate(kind, threshold, …)'),graphNode('contract',620,180,'«Protocol» RuleStrategy','fails(context, threshold): bool'),graphNode('quorum',290,370,'Quorum','Katılım eşiği'),graphNode('support',600,370,'HighSupport / MinoritySupport','Destek eşikleri'),graphNode('remaining',910,370,'ExpertReviewRequired / DescriptionLength','Görüş ve gerekçe koşulları')],edges:[edge('api','decisions','çağırır'),edge('decisions','engine','kullanır'),edge('engine','contract','strateji seçer'),edge('quorum','contract','gerçekleştirir',true),edge('support','contract','gerçekleştirir',true),edge('remaining','contract','gerçekleştirir',true)],notes:['GoF deseni: Strategy. Kurucu üzerinden strateji sözlüğü verilmesi bağımlılık enjeksiyonudur; ayrı bir GoF deseni olarak sayılmaz.','PolicyContext HTTP ve veritabanından bağımsızdır. Tanınmayan kural türü güvenli biçimde BLOCKED sonucu üretir.']}
}

function DesignPanel(){const [params,setParams]=useSearchParams();const requested=params.get('diagram')||'classes';const selected=['classes','usecases','sequence','strategy','state'].includes(requested)?requested:'classes';const setSelected=(value:string)=>setParams(previous=>{previous.set('tab','design');previous.set('diagram',value);return previous});const diagram=diagrams[selected];return <><div className="eng-intro"><div><h2>Uygulamanın tasarımını görünür kıl</h2><p>Alan ilişkileri, kullanım durumları, işlem sırası ve değiştirilebilir kural algoritmaları.</p></div><span className="eng-chip">Kodla eşleşen tasarım</span></div><Notice kind="info">Bu çizimler kodun yapısını ve iş akışını anlatan tasarım modelleridir. <Link to="/graph">İlişki haritası</Link> ise mevcut kullanıcı, takım, konu ve oy kayıtlarından canlı üretilir. Yakınlaştırma düğmeleriyle ayrıntıları büyütebilirsin.</Notice><div className="eng-diagram-options" aria-label="Diyagram seçimi">{[['classes','Sınıflar'],['usecases','Kullanım durumları'],['sequence','Sekans'],['strategy','Strategy ve bağımlılıklar'],['state','Durum akışı']].map(([id,text])=><button className={`button ${id===selected?'primary':'secondary'}`} key={id} aria-pressed={id===selected} onClick={()=>setSelected(id)}>{text}</button>)}</div>
  {selected==='sequence'?<SequenceDiagram/>:<div className="panel eng-diagram-panel"><h3>{diagram.title}</h3><p>{diagram.description}</p><div className="eng-flow" role="img" aria-label={diagram.title}><ReactFlow key={selected} nodes={diagram.nodes} edges={diagram.edges} fitView fitViewOptions={{padding:.15}} minZoom={.3} maxZoom={1.5} nodesDraggable={false} nodesConnectable={false} elementsSelectable={false} preventScrolling={false}><Background/><Controls showInteractive={false}/></ReactFlow></div><ul className="eng-notes">{diagram.notes.map(n=><li key={n}>{n}</li>)}</ul><details><summary>İlişkilerin metin karşılığı</summary><ul>{diagram.edges.map(e=><li key={e.id}>{diagram.nodes.find(n=>n.id===e.source)?.id} → {diagram.nodes.find(n=>n.id===e.target)?.id}: {String(e.label)}</li>)}</ul></details></div>}
  <p className="eng-source">Ders kaynağı: tasarim_desenleri.pdf · fiziksel sayfa 8: UML sınıf gösterimi; sayfa 9: SOLID. Diyagramlar bu uygulamanın mevcut model ve servislerini özetler.</p>
  </>}
